apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:latest
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "pass"
        ports:
        - containerPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:latest
        env:
        - name: SERVICES
          value: "s3"
        ports:
        - containerPort: 4566

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registro-voti-api
spec:
  selector:
    matchLabels:
      app: registro-voti-api
  template:
    metadata:
      labels:
        app: registro-voti-api
    spec:
      containers:
      # Modifica questa immagine con il nome del tuo account DockerHub se la carichi lì!
      - name: api
        image: docker-app:latest 
        imagePullPolicy: Never # Usa l'immagine costruita localmente dal tuo Docker
        env:
        - name: PORT
          value: "3000"
        - name: MONGO_DB
          value: "registro_voti"
        - name: MONGO_URI
          value: "mongodb://root:pass@mongo:27017/registro_voti?authSource=admin&w=majority"
        - name: AWS_ENDPOINT_URL
          value: "http://localstack:4566"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          value: "test"
        - name: AWS_SECRET_ACCESS_KEY
          value: "test"
        - name: AWS_S3_BUCKET_NAME
          value: "document-bucket"
        ports:
        - containerPort: 3000