apiVersion: apps/v1
kind: Deployment
metadata:
  name: registro-voti-api
spec:
  replicas: 1 # Quante copie dell'app vogliamo accese
  selector:
    matchLabels:
      app: registro-voti
  template:
    metadata:
      labels:
        app: registro-voti
    spec:
      containers:
      - name: api
        image: mia-api-go:latest
        imagePullPolicy: Never # IMPORTANTE: dice a K8s di usare l'immagine locale creata da Jenkins, senza cercarla su internet
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_DB
          value: "registro_voti"
        - name: MONGO_URI
          # NOTA: host.docker.internal funziona se usi K8s di Docker Desktop. 
          # Se usi Minikube potrebbe servire una piccola modifica qui.
          value: "mongodb://host.docker.internal:27017"