apiVersion: v1
kind: Service
metadata:
  name: registro-voti-service
spec:
  type: NodePort # Permette di esporre la porta all'esterno del cluster
  selector:
    app: registro-voti
  ports:
    - port: 8080
      targetPort: 3000 # La porta interna della tua app Fiber
      nodePort: 30082 # La porta da cui accederai tu dal browser (K8s accetta solo porte da 30000 in su per i NodePort)