services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  agent-golang:
    build:
      context: .
      dockerfile: golang.Dockerfile
    container_name: jenkins-agent-golang
    volumes:
      - jenkins_agent_golang:/var/jenkins
    depends_on:
      - jenkins

  agent-docker:
    build:
      context: .
      dockerfile: docker.Dockerfile
    container_name: jenkins-agent-docker
    volumes:
      - jenkins_agent_docker:/var/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins

  agent-kubectl:
    build:
      context: .
      dockerfile: kubectl.Dockerfile
    container_name: jenkins-agent-kubectl
    volumes:
      - jenkins_agent_kubectl:/var/jenkins
      - ~/.kube:/home/jenkins/.kube:ro
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=2ae97a66e8e9e9cfd740c73127a1e842a7f613e6d7615518cbbfd84464d5f05b
      - JENKINS_AGENT_NAME=agent-kubectl
    depends_on:
      - jenkins

volumes:
  jenkins_home:
  jenkins_agent_golang:
  jenkins_agent_docker:
  jenkins_agent_kubectl: